from flask import Flask, request, jsonify
import requests
from decouple import config
from functools import wraps
import db

app = Flask(__name__)

# APP CONFIGS:
twofactor_api_key = config('TWOFACTOR_API_KEY')


# DECORATORS:
def verifyOTP(f=None):
    @wraps(f)
    def _verifyOTP(*args, **kwargs):
        # Testing Values - 
        #   "sessionId": "34ed02e8-cf8b-4546-9380-226b8517b3fc"
        #   "otp": "235826"
        if not 'sessionId' in request.json:
            return jsonify({ "error": "SessionID not found in request body!"}), 400
        session_id = request.json['sessionId']
        if not 'otp' in request.json:
            return jsonify({ "error": "OTP not found in request body!"}), 400
        otp_input = request.json['otp']
        twoFactResp = requests.get(f'https://2factor.in/API/V1/{twofactor_api_key}/SMS/VERIFY/{session_id}/{otp_input}').json()
        if twoFactResp['Status'] == 'Error':
            return jsonify(twoFactResp)
        return f(*args, **kwargs)
    return _verifyOTP

# API ENDPOINTS: 

# Note: DO NOT CALL THIS API ENDPOINT AS THE AMOUNT OF CREDIT IS LIMITED
@app.route("/getotp")
def get_otp():
    if not 'phone' in request.headers:
        return jsonify({ "error": "Phone number not found in request header!"}), 400
    phone_number = request.headers['phone']
    if not phone_number or not len(phone_number) == 10:
        return jsonify({ "error": "The provide phone number is Invalid!"}), 400
    # twoFactResp = requests.get(f'https://2factor.in/API/V1/{twofactor_api_key}/SMS/{phone_number}/AUTOGEN').json()
    # return jsonify(twoFactResp)
    return "Success"
    # Expected Success Response -
    # {
    #     "Details": random id generated by uuid v4,
    #     "Status": "Success"
    # }
# ======================================================================

@app.route("/login")
def login():
    return "Login"

@app.route("/signup")
@verifyOTP
def signup():
    if not 'voterId' in request.json:
        return jsonify({ "error": "Invalid request!"}), 400
    if not 'fullName' in request.json:
        return jsonify({ "error": "Invalid request!"}), 400
    if not 'address' in request.json:
        return jsonify({ "error": "Invalid request!"}), 400
    if not 'phoneNumber' in request.json:
        return jsonify({ "error": "Invalid request!"}), 400
    voterId = request.json['voterId']
    checkId = db.get_user_by_voterId(voterId)
    if not len(checkId) == 0:
        return jsonify({ "error": "User already exists! Login Instead" }), 400
    phoneNumber = request.json['phoneNumber']
    fullName = request.json['fullName']
    address = request.json['address']
    data = db.create_user(voterId, fullName, address, phoneNumber)
    return data

@app.route("/")
def home():
    return "Hello World"

if __name__ == "__main__":
    app.run(debug=True)